project:
  type: book
  output-dir: _output
  execute-dir: project

from: markdown+emoji

book:
  title: ""
  subtitle: ""
  author: ""
  date: ""
  date-format: ""
  navbar:
    search: true
    pinned: true
  chapters:
    - part: Introduction
      chapters:
        - index.qmd

    - part: "Part 1"
      chapters:
        - 
        - 

    - part: Appendix
      chapters:
        - 

    - part: manuscript/references.qmd

execute: 
  freeze: auto
  cache: true
  
engine: knitr

cite-method: citeproc
csl: _assets/harvard-cite-them-right.csl
bibliography: manuscript/references.bib

code-block-bg: true
code-block-border-left: "#EF9F76"
highlight-style: oblivion
code-line-numbers: true
code-overflow: wrap

# Visual settings
code-block-bg: true
code-block-border-left: "#EF9F76"
highlight-style: ayu
code-line-numbers: true
code-overflow: wrap

# Figure settings
fig-prefix: "Figure"
fig-height: 18
fig-width: 22
fig-cap-location: bottom

# Typography
mainfont: "Liberation Sans"

# Numbering
number-sections: true
number-depth: 3

# Table of contents
toc-depth: 6
toc-expand: true
toc-title: "Contents"

# Resources
resources:
  - "_assets/images"
  
format:
  html:
    code-fold: true
    code-tools: true
    code-summary: View code cell contents
    default-image-extension: svg
    fig-format: svg
    theme: _assets/styles/frappe.scss
    toc: true
    toc-location: right-body #body, left-body, right-body, left, right
    page-layout: full
    gutter-width: 0.5em
  pdf: 
      keep-tex: true
      code-block-border-left: false
      geometry:
        - heightrounded
        - paperwidth=8.5in
        - paperheight=11in
        - left=1in
        - top=1in
        - bottom=1in
        - textwidth=26.5pc # changes width of main body text
        - marginparsep=2pc   
        - marginparwidth=15pc # changes width towards the right of margin text
        - textheight=44\baselineskip
        - headheight=\baselineskip
        - headsep=2\baselineskip
      mainfont: Inter
      monofont: Courier New
      monofontoptions: Scale=0.75
      pdf-engine: xelatex
      default-image-extension: png
      toc: true
      toc-depth: 6
      fig-format: png
      fig-width: 8
      fig-height: 6
      fig-cap-location: bottom
      fig-prefix: "Figure"
      number-sections: true
      template: _assets/basic_pdf_template.tex
      include-in-header:
        text: |
          \usepackage{longtable}
          \usepackage{booktabs}
          \usepackage{placeins}
          \let\oldlongtable\longtable
          \let\endoldlongtable\endlongtable
          \renewenvironment{longtable}{\FloatBarrier\oldlongtable}{\endoldlongtable\FloatBarrier}
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
            breaklines,
            breaksymbolleft={},
            showspaces=false,
            showtabs=false,
            commandchars=\\\{\}
          }

reference-location: margin
citation-location: document

custom-callout: #https://github.com/coatless-quarto/custom-callout/
  h0:
    title: "Null Hypothesis" 
    icon-symbol: ❔
    color: "#EF9F76"
  h1:
    title: "Alternative Hypothesis" 
    icon-symbol: ❓
    color: "#8CAAEE"
  question:
    title: "Research Question" 
    icon-symbol: 💭
    color: "#EF9F76"
  report:
    title: "Report Package Summary" 
    icon-symbol: 🗒
    color: "#BABBF1"
    collapse: true
  quote:
    title: "Definition"
    icon-symbol: "fa-quote-left"
    color: "#414559"
filters:
  - custom-callout

knitr:
  opts_chunk:
    R.options:
      knitr.graphics.auto_pdf: true
      knitr.duplicate.label: allow
    echo: true
    message: false
    warning: false
    eval: false
    #collapse: true #if possible, collapse source and output blocks from one code chunk
    results: hold
    cache.size: 4000
    error: false # set true to complete render even if there are errors
    fig-caption: true
    fig-width: 12
    fig-height: 8
    fig-pos: "h"
    fig-align: "left"
    dpi: 300
    fig.width: 10
    fig.height: 8
    fig.show: "hold"
    out.width: "0.8\\linewidth"
    comment: "" #the prefix to be added before each line of the text output.
    ft.latex.float: 'float'
    ft.split: false
    ft.align: "center"
    ft.tabcolsep: 5
    prompt: false
  opts_knit: #controls the output of quarto render in the terminal
    verbose: true
